require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/inferno/terminology/**'

# Use code climate's metrics measurement rather than rubocop's
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

Gemspec/RequireMFA:
  Enabled: false
