version: '3.2'
services:
  terminology_builder:
    image: onc-certification-g10-test-kit-terminology_builder:latest
    volumes:
      - ./data:/opt/inferno/data
      - type: bind
        source: "./resources/terminology"
        target: "/opt/inferno/resources/terminology"
        consistency: delegated
      - type: bind
        source: "./tmp"
        target: "/opt/inferno/tmp"
        consistency: delegated
    environment:
      UMLS_API_KEY:
      CLEANUP:
